name: Deploy netlify example site

on:
  push:
    branches: 
      - examples
  pull_request:
    branches: 
      - examples
    types:
      - closed
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Deploy site"
        run: curl -X POST -d {} ${{ secrets.NETLIFY_EXAMPLE_BUILD_HOOK }}
