name: "Tests"

on:
  push:
    paths-ignore:
      - "docs/**"
    branches: 
      - main
  pull_request:
    paths-ignore:
      - "docs/**"
    branches: 
      - main
    types: 
      - opened
      - reopened
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 20.16.0
          registry-url: https://registry.npmjs.org
      - name: Install dependencies
        run: bun install
      - run: bun run lint
      - run: bun run test
